name: Build Editor

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, ubuntu-latest]

    steps:

      - uses: actions/checkout@v2
        with:
          ref: electron

      - name: Set env
        shell: bash
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}

      - name: See env
        run: echo "${{ env.RELEASE_VERSION }}"

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      
      - name: Secrets
        run: |
          echo "Secret: " ${{ secrets.GITHUB_TOKEN }}
          echo "Secret: " ${{ secrets.EDITOR_SECRET }}
        

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: See directory
        run: ls dist/*.*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          files: dist/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
        
