name: Build Editor

on:
  push:
    branches:
      - electron

jobs:
  build:
    name: Build Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]

    steps:

      - uses: actions/checkout@v2
        with:
          ref: electron

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export

      - name: Upload builds to release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
