name: Build Editor

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:

      - uses: actions/checkout@v2
        with:
          ref: electron

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export

      - name: See directory
        run: ls ./dist/*

      - name: Echo tag version
        id: get_version 
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} 
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
        
