name: Build Editor

on:
  push:
    branches:
      - electron

jobs:
  build:
    name: Build Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]

    steps:

      - uses: actions/checkout@v2
        with:
          ref: electron

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'
          
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export

      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: dist/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.EDITOR_SECRET }}
