name: Build Nightly Grid Editor

on: 
  push:
    branches:
      - nightly

jobs:
  build:
    if: github.ref == 'refs/heads/nightly'
    name: Build Nightly Grid Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-2016, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ''
          submodules: true

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export
        env:
          # gh repo token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # macOS Code signing certificates
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

          # macOS notarization API key
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: See directory
        run: ls dist/*.*

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          
      - name: Display structure of downloaded files
        run: ls -R