name: Build Nightly Grid Editor

on: 
  push:
    branches:
      - stable

jobs:
  job_1:
    name: Build Nightly Grid Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ''
          submodules: true

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '14.4'

      - name: create  file
        run: |
          touch test_file
          echo "hello" >> test_file
          ls -l

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nightly
          path: test_file
    

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nightly
      
      - name: Create Archive
        run: |
          ls -l
          tar -cvf deploy.tar test_file
          ls -l
      
      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          source: "deploy.tar"
          target: "/volume1/shared/"

      - name: Discord Notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            username: Nightly Bot
            footer: Programming is fun.
            description: 'Download latest nightly artifact!'
            details: 'Link to workflows: https://github.com/intechstudio/grid-editor/actions'
            webhookUrl: ${{ secrets.DISCORD_DEV_WEBHOOK }}
