name: Build Nightly Grid Editor

on: 
  push:
    branches:
      - stable

jobs:
  job_1:
    name: Build Nightly Grid Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: create  file
        run: |
          touch test_file
          echo "hello" >> test_file
          ls -l

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nightly
          path: test_file
    

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nightly
      
      - name: Create Archive
        run: |
          ls -l
          tar -cvf deploy.tar test_file
          ls -l
      
      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          source: "deploy.tar"
          target: "/volume1/shared/test"

  
